version: '3.8'

services:
  frontend:
    image: 191413ai-frontend:latest
    build:
      context: .
      dockerfile: Dockerfile.production
    container_name: 191413ai-frontend
    restart: always
    env_file: .env.production
    expose:
      - 3000
    environment:
      - VIRTUAL_HOST=191413.ai
      - VIRTUAL_PORT=3000
      - LETSENCRYPT_HOST=191413.ai
      - LETSENCRYPT_EMAIL=77eshike@gmail.com
    networks:
      - web
      - internal

  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    restart: always
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - nginx_certs:/etc/nginx/certs
      - nginx_vhost:/etc/nginx/vhost.d
      - nginx_html:/usr/share/nginx/html
      - ./certbot/conf:/etc/nginx/conf.d
    networks:
      - web

  nginx-letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: nginx-letsencrypt
    restart: always
    environment:
      - NGINX_PROXY_CONTAINER=nginx-proxy
      - DEFAULT_EMAIL=77eshike@gmail.com
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - nginx_certs:/etc/nginx/certs
      - nginx_vhost:/etc/nginx/vhost.d
      - nginx_html:/usr/share/nginx/html
    depends_on:
      - nginx-proxy
    networks:
      - web

networks:
  web:
    external: false
  internal:
    external: false

volumes:
  nginx_certs:
  nginx_vhost:
  nginx_html:
