services:
  frontend:
    container_name: 191413ai-frontend
    build:
      context: .
      dockerfile: frontend/Dockerfile
    volumes:
      - .:/usr/src/app
    networks:
      - web
    environment:
      - VIRTUAL_HOST=191413.ai
      - VIRTUAL_PORT=3000
      - LETSENCRYPT_HOST=191413.ai
      - LETSENCRYPT_EMAIL=77eshike@gmail.com
    expose:
      - "3000"
    restart: always

networks:
  web:
    external: true
