# 使用 Node.js 官方 Alpine 镜像
FROM node:20-alpine as storybook

# 设置工作目录
WORKDIR /app

# 拷贝依赖文件并安装
COPY package*.json ./
RUN npm install --legacy-peer-deps

# 拷贝项目源码
COPY ./src ./src
COPY ./public ./public
COPY .storybook ./.storybook
COPY next.config.js ./
COPY tsconfig.json ./

# 构建 Storybook 静态站点
RUN npm run build-storybook
