#!/usr/bin/env sh
[ "${HUSKY:-1}" = "0" ] && exit 0

# 是否有暂存代码
if git diff --cached --name-only --diff-filter=ACMR | grep -q .; then
  echo "🔍 lint-staged running..."
  npx --no -- lint-staged || exit 1
else
  echo "→ No staged files."
fi
